### ISSUE TITLE
"Magic number is not correct!");

### ISSUE THREAD

**Issue by guominfang** [TinyNiko/mac_wxapkg_decrypt#11]
Error: Magic number is not correct!
    at header (/Users/mac/Documents/github/WxAppUnpacker1/wuWxapkg.js:21:54)
    at /Users/mac/Documents/github/WxAppUnpacker1/wuWxapkg.js:186:44
    at /Users/mac/Documents/github/WxAppUnpacker1/wuLib.js:95:14
    at agent (/Users/mac/Documents/github/WxAppUnpacker1/wuLib.js:64:23)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

Node.js v20.3.1
node /Users/mac/Documents/github/WxAppUnpacker1/wuWxapkg.js temp/h.wxapkg
Unpack file temp/h.wxapkg...

**Comment by TinyNiko** [comment]
来个小程序看看
